apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
  namespace: argocd
  
spec:
  description: Cert-Manager

  sourceRepos:
    - 'https://github.com/ros-nett/cert-manager.git'

  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
      
  clusterResourceWhitelist:
    - group: 'apiextensions.k8s.io'
      kind: 'CustomResourceDefinition'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRoleBinding'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRole'
    - group: 'admissionregistration.k8s.io'
      kind: 'MutatingWebhookConfiguration'
    - group: 'admissionregistration.k8s.io'
      kind: 'ValidatingWebhookConfiguration'
    - group: 'cert-manager.io'
      kind: '*'
    - group: ''
      kind: 'Namespace'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    name: cert-manager
spec:
  project: cert-manager

  source:
    repoURL: https://github.com/ros-nett/cert-manager.git
    targetRevision: HEAD
    path: base

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
