apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sealed-secrets
  namespace: argocd
  
spec:
  description: Sealed Secrets

  sourceRepos:
    - 'https://github.com/ros-nett/sealed-secrets.git'

  destinations:
    - namespace: sealed-secrets
      server: https://kubernetes.default.svc
      
  clusterResourceWhitelist:
    - group: 'apiextensions.k8s.io'
      kind: 'CustomResourceDefinition'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRoleBinding'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRole'
    - group: ''
      kind: 'Namespace'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    name: sealed-secrets
spec:
  project: sealed-secrets

  source:
    repoURL: https://github.com/ros-nett/sealed-secrets.git
    targetRevision: HEAD
    path: base

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
