apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: traefik
  namespace: argocd

spec:
  description: Traefik Ingress controller

  sourceRepos:
    - 'https://helm.traefik.io/traefik'

  destinations:
    - namespace: traefik
      server: https://kubernetes.default.svc

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: ingress
spec:
  project: traefik

  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: HEAD

    chart: traefik
    helm:
      version: v3

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
