apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-apps
  namespace: argocd

spec:
  description: ArgoCD App of Apps project

  sourceRepos:
    - 'https://github.com/ros-nett/argocd-apps.git'

  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
  labels:
    name: argocd
spec:
  project: argocd-apps

  source:
    repoURL: https://github.com/ros-nett/argocd-apps.git
    targetRevision: HEAD
    path: base

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
